version: '3'
services:
  php:
    build: build/php
    expose:
    - '9000'
    depends_on:
    - db
    volumes:
    - ./symfony:/var/www/html/symfony:cached
    - ./logs:/var/log
  web:
    build: build/nginx
    restart: always
    ports:
    - '81:80'
    depends_on:
    - php
    - db
    volumes:
    - ./symfony:/var/www/html/symfony:cached
    - ./logs:/var/log/nginx
  db:
    image: mysql/mysql-server:5.6
    environment:
    - MYSQL_DATABASE=FuzzyDuplicates
    - MYSQL_ROOT_PASSWORD=RootPassword123
    - MYSQL_USER=FuzzerUser
    - MYSQL_PASSWORD=FuzzerPassword123
    ports:
    - '3307:3306'
    volumes:
    - ./mysql:/var/lib/mysql