version: '3'
services:
  php:
    build: build/php
    expose:
    - '9000'
    depends_on:
    - db
    volumes:
    - ./symfony:/var/www/html/symfony:cached
    - ./logs:/var/log
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
  web:
    build: build/nginx
    restart: always
    ports:
    - '81:80'
    depends_on:
    - php
    - db
    volumes:
    - ./symfony:/var/www/html/symfony:cached
    - ./logs:/var/log/nginx
  db:
    build: build/mysql
    ports:
    - '3307:3306'
    volumes:
    - ./mysql:/var/lib/mysql